### PR TITLE
Various documentation fixes

### PR DESCRIPTION
**Pull request by waldyrious**
Changes applied are as follows (each corresponding to its own commit):

- Fix typos (4039752)
- Adjust word separation (e65cd93)
- Fix capitalization of acronyms (b74a1d3)
- Clarify possessives (25ec2fa)
- Various assorted fixes (3f8d42b)
- Fix whitespace (1f08681)

I would strongly recommend reviewing each commit's diff separately, to ensure the highlighting is properly applied so the changes are intelligible.

### CODE REVIEW

**Comment by macdonst** [comment]
@waldyrious, thanks for the PR. I'm going to merge in your changes but in `app/docs/md/reference/libraries/enhance-style-transform.md` we are using `descendent` correctly as it is an adjective and not a noun.

**Comment by waldyrious** [comment]
Thanks for merging!

> in `app/docs/md/reference/libraries/enhance-style-transform.md` we are using `descendent` correctly as it is an adjective and not a noun.

Hmm, I'm not sure I can follow the logic. In the expression "general descendent selector", "general" is indeed an adjective qualifying "descendent", and the combined expression "general descendant" works as an [atributive noun](https://en.wikipedia.org/wiki/Noun_adjunct) that modifies "selector". The fact that the expression acts as a noun modifier [does not necessarily make it an adjective](https://www.britannica.com/dictionary/eb/qa/Nouns-that-act-like-Adjectives-attributive) — that would require e.g. the ability to be inflected into comparative and superlative forms, e.g. it should be possible to say things like "descendenter selector", which is not the case.

That said, I realized I also missed a similar fix in `app/docs/md/learn/features/transforms/style-transforms.md` :see_no_evil::
 
https://github.com/enhance-dev/enhance.dev/blob/42ec3ecdaca864f016dc4ffeffc0a439b09fcb46/app/docs/md/learn/features/transforms/style-transforms.md#L156

If the above makes sense to you, I'd be happy to provide the fix for this file as well as a separate PR.

**Comment by macdonst** [comment]
@waldyrious hmmm…I was always taught only to use descendant if it was a living thing but it looks like they are called descendant selectors in CSS so I will make the change. When in doubt check MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator

Again, thanks for the PR. Sorry, it took a bit to get to it. Have you been using Enhance on a project?

**Comment by waldyrious** [comment]
Yeah, as a non-native speaker, I know well how English spelling can be tricky :) relying on MDN sounds like a good idea.

> Again, thanks for the PR. Sorry, it took a bit to get to it.

No worries! I am well aware that work in open source projects often happens in bursts, as life permits, and had no expectations of a fast response. Thank you for incorporating the changes! 

> Have you been using Enhance on a project?

Not yet, but I really want to! Unfortunately (or perhaps fortunately) I only do frontend development in hobby projects, and time for those is scarce nowadays with family life and the day job, so it may take a while until I get the opportunity to try it out. But meanwhile I'm following the project with interest!

**Pull request merged**
