### PR TITLE
style: smooth scroll behaviour

### LINKED ISSUE #146: Back to the top! smooth behaviour
Hi team!
The Back to the top! link at the end of the landing page can be improved. As on clicking it, it should feel like we are scrolling back to the top, but right now it does not seem to be working in this way.

### PR DESCRIPTION
**Pull request by hsnice16**
fix #146

### CODE REVIEW

**Review by colepeters — CHANGES_REQUESTED** [review]
Thanks for this!

One thing we need to make sure of, though, is that folks who get motion sickness or other side effects from motion/animation don't wind up seeing this animation. This would be easy to do by putting your change (`scroll-behavior: smooth;`) behind a `prefers-reduced-motion: no-preference` media query. This way, only people who have _not_ set this preference in their system's accessibility settings will get the smooth scrolling behavior.

Mind making this update? (Or I can if you'd prefer.)

Thanks again!

**Comment by kristoferjoseph** [comment]
Another minor note is to try and keep your PR changes specific to the issue.
If your linter, prettier, what have you is different than the one the project is using it makes the pull request harder to review since it introduced more changes in unrelated files.

**Comment by hsnice16** [comment]
Thanks for mentioning it, @kristoferjoseph 
I will keep it in mind.

**Review by colepeters — APPROVED** [review]
Right on, thank you! Much appreciated ☺️

**Pull request merged**
