### PR TITLE
Issue #104: Routes without trailing slash lead to 404

### PR DESCRIPTION
**Pull request by macdonst**
Signed-off-by: macdonst <simon.macdonald@gmail.com>

### CODE REVIEW

**Comment by tbeseda** [comment]
I agree with the text of issue #104 : it could _redirect_ but I'm not sure we should render at that path.

This one is a bit more nuanced since trailing slashes have meaning here and while this app likely intends to render `routing/index.md` when a user hits `/routing`, it's technically different and there are some side effects.

1. It would crash into `/routing.md` if we had one -- which we _shouldn't_ add, but it's possible in the current .md router
1. 404s get weird when the trailing slash is missing and index.md is added
1. Also it messes up the "Edit on GitHub" link. For example, this `/routing` path creates [this broken link](https://github.com/enhance-dev/enhance.dev/edit/main/app/docs/md/learn/concepts/routing.md). 

IMO it should 302 redirect to `/routing/` if it knows `/routing/index.md` exists.  
So that would make it a part of the error handling instead of the render step. Basically use an `existsSync` check

**Comment by tbeseda** [comment]
OR we go with the alternative router I was kicking around where there are no index files.
So instead of `routing/index.md` + `routing/lifecycle.md` + the other nested .md files.  
We'd have `routing.md` + `routing/lifecycle.md` + the rest still in the routing folder.

(btw, I am omitting the rest of the path (`learn/concepts/.`) above routing to make it easier to think about)

**Comment by macdonst** [comment]
@tbeseda great feedback. What if we line up with the way Enhance does things and use:

`routing.md` + `routing/lifecycle.md`

**Comment by tbeseda** [comment]
> @tbeseda great feedback. What if we line up with the way Enhance does things and use:
> 
> `routing.md` + `routing/lifecycle.md`

I like it! Symmetry is nice for my brain  
fun fact: I wrote the "arcdown-router" package that became this site prior to Enhance routes being settled and I tried to base it on my PHP days, which in retrospect was the wrong model to follow 😜

**Comment by macdonst** [comment]
@tbeseda unfortunately, if I rename the files, we have the opposite problem.

**Comment by macdonst** [comment]
@tbeseda I ended up doing a redirect instead. Please give it a once over.

**Review by tbeseda — APPROVED** [review]

**Pull request merged**
